# Generated by Django 5.1.4 on 2026-03-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('user_id', models.CharField(default='test', max_length=255)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('result', models.TextField(blank=True, null=True)),
                ('migrated_count', models.IntegerField(default=0)),
                ('total_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FailedMigration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, max_length=255)),
                ('user_id', models.CharField(default='test', max_length=255)),
                ('file_id', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=500)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['task_id'], name='drive_faile_task_id_87ad1a_idx'), models.Index(fields=['user_id'], name='drive_faile_user_id_15abda_idx')],
            },
        ),
    ]
