# Generated by Django 5.1.4 on 2025-01-23 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmailapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_active',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 1, 23, 18, 1, 34, 165174, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
