# Generated by Django 5.1.4 on 2025-01-23 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmailapp', '0002_alter_customuser_last_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_active',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 1, 23, 18, 18, 23, 12148, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
