# Generated by Django 5.1.4 on 2025-01-24 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmailapp', '0003_alter_customuser_last_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_active',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 1, 24, 13, 31, 21, 350770, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
