# Generated by Django 5.1.4 on 2025-01-13 11:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmailapp', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='user_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
