# Generated by Django 5.1.4 on 2025-03-28 02:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmailapp', '0008_alter_customuser_last_active_useroauthclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_active',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 3, 28, 2, 55, 58, 127727, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
