# Generated by Django 5.1.4 on 2025-01-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmailapp', '0008_taskstatus_delete_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstatus',
            name='deleted_count',
            field=models.IntegerField(default=0),
        ),
    ]
