# Generated by Django 5.1.4 on 2025-01-14 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmailapp', '0010_recoverstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recoverstatus',
            old_name='deleted_count',
            new_name='recover_count',
        ),
    ]
