# Generated by Django 5.1.4 on 2025-01-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmailapp', '0011_rename_deleted_count_recoverstatus_recover_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yash', models.CharField(max_length=20)),
            ],
        ),
    ]
