# Generated by Django 5.1.4 on 2025-01-15 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmailapp', '0012_myname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Myname',
        ),
    ]
