# Generated by Django 5.1.4 on 2025-01-21 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmailapp', '0002_alter_recoverstatus_user_alter_taskstatus_user_and_more'),
        ('gmailapp', '0015_alter_taskstatus_user_alter_recoverstatus_user_and_more'),
    ]

    operations = [
    ]
