# Generated by Django 5.1.4 on 2025-01-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gmailapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.EmailField(max_length=255)),
                ('thread_id', models.CharField(max_length=255)),
            ],
        ),
    ]
