# Generated by Django 5.1.4 on 2025-01-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmailapp', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yash', models.TextField(default='yah')),
            ],
        ),
    ]
