# Generated by Django 5.1.4 on 2025-01-01 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmailapp', '0003_alter_gmail_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gmail',
        ),
    ]
