# Generated by Django 5.1.4 on 2025-01-01 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmailapp', '0003_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='email',
        ),
    ]
