# Generated by Django 5.1.4 on 2025-01-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmailapp', '0004_delete_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gmail',
            name='message_id',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='gmail',
            name='thread_id',
            field=models.CharField(max_length=1000),
        ),
    ]
