# Generated by Django 5.1.4 on 2025-01-13 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmailapp', '0006_email_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='customer',
        ),
    ]
